// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKki3dTuvEPDzUh0d9JTnGX1ikqUdIvHE',
    appId: '1:614712437712:web:c366595e505943aa9067d5',
    messagingSenderId: '614712437712',
    projectId: 'movie-app-91e24',
    authDomain: 'movie-app-91e24.firebaseapp.com',
    storageBucket: 'movie-app-91e24.appspot.com',
    measurementId: 'G-V1Z6VH8WJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARo3qjLRHdIN5Uf7GvafC6whlXf33Iyj8',
    appId: '1:614712437712:android:8d8bbde02bce33dd9067d5',
    messagingSenderId: '614712437712',
    projectId: 'movie-app-91e24',
    storageBucket: 'movie-app-91e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEX1yv6nKov3ys23tLNXHzHZeDvBvsSA',
    appId: '1:614712437712:ios:edc3593d5739de339067d5',
    messagingSenderId: '614712437712',
    projectId: 'movie-app-91e24',
    storageBucket: 'movie-app-91e24.appspot.com',
    iosBundleId: 'com.example.movies3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEX1yv6nKov3ys23tLNXHzHZeDvBvsSA',
    appId: '1:614712437712:ios:24bad0307c18a4519067d5',
    messagingSenderId: '614712437712',
    projectId: 'movie-app-91e24',
    storageBucket: 'movie-app-91e24.appspot.com',
    iosBundleId: 'com.example.movies3.RunnerTests',
  );
}
